[package]
name = "nsi-mitsuba"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0 OR Zlib"
description = "Mitsuba 3 backend for the Nodal Scene Interface – ɴsɪ."
repository = "https://github.com/virtualritz/nsi-mitsuba/"

[dependencies]
nsi-record = { version = "0.1", path = "../nsi-record" }
